# Generated by Django 4.1.7 on 2023-04-09 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=150)),
                ("fullname", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=150)),
                ("security_question_1", models.CharField(max_length=500)),
                ("answer_1", models.CharField(max_length=500)),
                ("security_question_2", models.CharField(max_length=500)),
                ("answer_2", models.CharField(max_length=500)),
            ],
        ),
    ]
