# Generated by Django 4.1.7 on 2023-04-16 04:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="deliveries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trackingid", models.CharField(max_length=100)),
                ("driver", models.CharField(max_length=150)),
                ("status", models.CharField(max_length=50)),
                ("current_city", models.CharField(max_length=100)),
                ("current_state", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="orders",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trackingid", models.CharField(max_length=100)),
                ("username", models.CharField(max_length=150)),
                ("orderdate", models.DateField()),
                ("destination_address", models.CharField(max_length=500)),
                ("source_address", models.CharField(max_length=500)),
                ("delivery_service", models.CharField(max_length=200)),
                ("package_weight", models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name="users",
            name="user_type",
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
