# Generated by Django 4.1.7 on 2023-04-21 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0002_deliveries_orders_users_user_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveries",
            name="latitude",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="deliveries",
            name="longitude",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
