# Generated by Django 4.1.7 on 2023-04-23 00:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0004_alter_deliveries_current_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="register_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
