# Generated by Django 4.1.7 on 2023-04-24 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0005_users_register_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="services",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("package_size", models.CharField(max_length=50)),
                ("price", models.FloatField()),
            ],
        ),
    ]
