# Generated by Django 4.1.7 on 2023-04-24 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0006_services"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="package_weight",
            field=models.CharField(max_length=50),
        ),
    ]
